/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CarDealerDataPackageProfile {
  dealer: Dealer;
  resources: [] | [CarResource];
  [k: string]: unknown;
}
export interface Dealer {
  title: string;
  url?: string;
  [k: string]: unknown;
}
export interface CarResource {
  name: "car";
  schema: "https://raw.githubusercontent.com/datisthq/cardealerdp/v0.1.1/schemas/car.json";
  [k: string]: unknown;
}
