/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CarDealerDataPackageProfile = Package;
export type Schema = "https://raw.githubusercontent.com/datisthq/cardealerdp/v0.1.0/schemas/car.json";

export interface Package {
  dealer: Dealer;
  /**
   * @minItems 1
   * @maxItems 1
   */
  resources: [Resource];
}
export interface Dealer {
  /**
   * A title for the dealer
   */
  title: string;
  url?: string;
}
export interface Resource {
  name: "car";
  schema: Schema;
}
