# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class Car(BaseModel):
    name: Optional[str] = None
    price: Optional[float] = None
