# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-10-01T15:42:37+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class Car(BaseModel):
    name: Optional[str] = None
    price: Optional[float] = None
