# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional

from pydantic import BaseModel, Field, RootModel


class Dealer(BaseModel):
    title: str = Field(..., description='A title for the dealer')
    url: Optional[str] = None


class Data(RootModel[List[Dict[str, Any]]]):
    root: List[Dict[str, Any]] = Field(
        ...,
        description='Data items have to be conformed to the Car data schema',
        min_length=1,
    )


class Schema(
    RootModel[
        Literal[
            'https://raw.githubusercontent.com/datisthq/cardealerdp/v0.1.0/schemas/car.json'
        ]
    ]
):
    root: Literal[
        'https://raw.githubusercontent.com/datisthq/cardealerdp/v0.1.0/schemas/car.json'
    ]


class Resource(BaseModel):
    name: Literal['car']
    data: Optional[Data] = None
    schema_: Schema = Field(..., alias='schema')


class Package(BaseModel):
    dealer: Dealer
    resources: List[Resource] = Field(..., max_length=1, min_length=1)


CarDealerDataPackageProfile = Package
