# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-10-02T07:51:03+00:00

from __future__ import annotations

from typing import List, Literal, Optional

from pydantic import BaseModel, Field, RootModel


class Dealer(BaseModel):
    title: str
    url: Optional[str] = None


class Schema(
    RootModel[
        Literal[
            'https://raw.githubusercontent.com/datisthq/cardealerdp/v0.1.0/schemas/car.json'
        ]
    ]
):
    root: Literal[
        'https://raw.githubusercontent.com/datisthq/cardealerdp/v0.1.0/schemas/car.json'
    ]


class Resource(BaseModel):
    name: Literal['car']
    schema_: Schema = Field(..., alias='schema')


class Package(BaseModel):
    dealer: Dealer
    resources: List[Resource] = Field(..., max_length=1, min_length=1)


CarDealerDataPackageProfile = Package
