/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A schema describing a car
 */
export interface Car {
  name?: string;
  /**
   * The price of the car
   */
  price: number;
}
